CREATE TABLE users (
    id                 UUID         NOT NULL,
    first_name         VARCHAR(100) NOT NULL,
    email              VARCHAR(150) NOT NULL,
    password           VARCHAR(150) NOT NULL,
    created_by         VARCHAR(100),
    created_date       TIMESTAMP WITH TIME ZONE,
    last_modified_by   VARCHAR(100),
    last_modified_date TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE roles_user (
    id   INTEGER     GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(40) NOT NULL,
    CONSTRAINT pk_roles_user PRIMARY KEY (id),
    CONSTRAINT uk_roles_user_name UNIQUE (name)
);

CREATE TABLE users_roles (
    user_id UUID    NOT NULL,
    role_id INTEGER NOT NULL,
    CONSTRAINT pk_users_roles PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_users_roles_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_users_roles_role FOREIGN KEY (role_id) REFERENCES roles_user (id)
);

INSERT INTO roles_user (name) VALUES ('ROLE_USER'), ('ROLE_ADMIN');
